package Batch108109ENG;

import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.By;
import utilities.TestBase;

public class Day07_Alerts extends TestBase {

    @Test
    public void acceptAlert() throws InterruptedException {
//        Go to https://the-internet.herokuapp.com/javascript_alerts
        driver.get("https://the-internet.herokuapp.com/javascript_alerts");
        Thread.sleep(2000);

//        acceptAlert() => click on the first alert,
        driver.findElement(By.xpath("//*[@onclick='jsAlert()']")).click();

//                verify the text “I am a JS Alert” ,
        String actualAlertText = driver.switchTo().alert().getText();
        String expectedalertText = "I am a JS Alert";
        Assert.assertEquals(expectedalertText, actualAlertText);
        Thread.sleep(2000);

//        click OK ,
        driver.switchTo().alert().accept();

//        and Verify “You successfully clicked an alert”
        String actualResult = driver.findElement(By.id("result")).getText();
        String expectedResult = "You successfully clicked an alert";
        Assert.assertEquals(expectedResult, actualResult);

    }

    @Test
    public void dismissAlert() throws InterruptedException {

        //Go to https://the-internet.herokuapp.com/javascript_alerts
        driver.get("https://the-internet.herokuapp.com/javascript_alerts");
        Thread.sleep(2000);//just uaing hard wait to execute slower to see the steps

//        dismissAlert()=> click on the second alert,
        driver.findElement(By.xpath("//*[@onclick='jsConfirm()']")).click();
        Thread.sleep(2000);

//                verify text "I am a JS Confirm”,
        String actualText = driver.switchTo().alert().getText();
        String expectedText = "I am a JS Confirm";
        Assert.assertEquals(expectedText, actualText);
        Thread.sleep(2000);

//        click cancel,
        driver.switchTo().alert().dismiss();

//        and Verify “You clicked: Cancel”
        String actualDismissText = driver.findElement(By.id("result")).getText();
        String expectedDismissText = "You clicked: Cancel";
        Assert.assertEquals(expectedDismissText, actualDismissText);

    }

    @Test
    public void sendkeysAlert() throws InterruptedException {

        //Go to https://the-internet.herokuapp.com/javascript_alerts
        driver.get("https://the-internet.herokuapp.com/javascript_alerts");
        Thread.sleep(2000);

//        sendKeysAlert()=> click on the third alert,
        driver.findElement(By.xpath("//*[@onclick='jsPrompt()']")).click();
        Thread.sleep(2000);

//                verify text “I am a JS prompt”,
        String actualPromptAlertText = driver.switchTo().alert().getText();
        String expectedPromptAlertText = "I am a JS prompt";
        Assert.assertEquals(expectedPromptAlertText, actualPromptAlertText);
        Thread.sleep(2000);

//        type “Hello World”,
        driver.switchTo().alert().sendKeys("Hello World");
        Thread.sleep(2000);

//        click OK,
        driver.switchTo().alert().accept();
        Thread.sleep(2000);

//        and Verify “You entered: Hello World”
        String actualResult = driver.findElement(By.id("result")).getText();
        String expectedResult = "You entered: Hello World";
        Assert.assertEquals(expectedResult, actualResult);

/*
    What is an alert?
    Alerts are a pop up that is generated by javascript.
    When there is an alerts, we must handle the alerts.
            Otherwise, we cannot continue to the test execution
    How do you handle alert?
    First we cannot inspect js alerts. We should first switch
    to the alert and use accept() to click ok, dismiss() to
    click cancel, sendKeys() to type, getText() to get the
    text from the alert

 */
    }
}